#!/usr/bin/env bash

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path="$1"
	server_ip="$2"
	username="$3"
	ssh_privatekey="$4"

	scp -oStrictHostKeyChecking=no -i "$ssh_privatekey" "$file_path" "$username@$server_ip:~/"
fi
