#!/usr/bin/env bash

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_privatekey="$4"

host_check="StrictHostKeyChecking=no"

if [ -n "$ssh_privatekey" ]; then
	scp -o$host_check -i "$ssh_privatekey" "$file_path" "$username@$server_ip:~/"
else
	scp -o$host_check "$file_path" "$username@$server_ip:~/"
fi
