#!/usr/bin/env bash
# Installs nginx in a server and adds a redirect link.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo sed -i '52a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
