#!/usr/bin/env bash
# Installs and configures HAProxy

sudo apt update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy


config_txt="
frontend load_balancer
	bind *:80
	mode http
	default_backend web_servers

backend web_servers
	mode http
	balance roundrobin
	server web-01 34.204.203.16:80 check
	server web-02 35.153.67.78:80 check
"

echo "$config_txt" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
