#!/usr/bin/env bash
# Script that tells a story with the /etc/passwd file

filename="/etc/passwd"

while IFS=: read -r u_name pass uid gid u_info home_dir shellz
do
    echo "The user $u_name is part of the $gid gang, lives in \
$home_dir and rides $shellz. $uid's place is protected by \
the passcode $pass, more info about the user here: $u_info"
done < $filename
