#!/usr/bin/env bash
# Changes the IP address for localhost and facebook

echo "127.0.0.2	localhost" > new_ips
echo "8.8.8.8	facebook.com" >> new_ips
echo >> new_ips

cat /etc/hosts | grep -v "localhost
facebook.com" >> new_ips

mv -f new_ips /etc/hosts
