#!/usr/bin/env bash
# Changes the IP address for localhost and facebook

{ echo "127.0.0.2	localhost";
  echo "8.8.8.8	facebook.com";
  echo;
} > ~/new_ips

cat < /etc/hosts >> ~/new_ips
sed -i s/^127\.0\.0\.1.*$// ~/new_ips
sed -i s/^[^8].*facebook.com$// ~/new_ips

mv -f ~/new_ips /etc/hosts
